 CREATE TABLE IF NOT EXISTS weather (
    id SERIAL PRIMARY KEY,
    city VARCHAR(255) NOT NULL,
    country_code VARCHAR(255) NOT NULL,
    data JSONB NOT NULL
 );

 CREATE TABLE IF NOT EXISTS location (
    id SERIAL PRIMARY KEY,
    city VARCHAR(255) NOT NULL,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL
 );

 CREATE TABLE IF NOT EXISTS parks (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    cost DECIMAL(10, 2) NOT NULL,
    description TEXT NOT NULL,
    url VARCHAR(255) NOT NULL
 );